version: 2.0.0-alpha{build}
branches:
  only:
  - master
  - develop
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: dd4t
  nuget_password:
    secure: oCp+uZEVnIgQBxhDObhLlg==
install:
- nuget sources add -Name Incentro -Source http://developer.incentro.com/nexus/service/local/nuget/tridion.net/ -UserName %nuget_user% -Password %nuget_password%
- choco install msbuild.communitytasks -y
build:
  project: build.msbuild
  verbosity: normal
artifacts:
- path: build/package/**/*.nupkg
  name: NuGet Package
- path: build/package/**/*.zip
  name: Zip Archive
deploy:
- provider: NuGet
  api_key:
    secure: QmYvNY2pkxjIhWiI/UwFB/rjAkoNhZpElLZhmXiNVKvasN3qRyvvag0/2ZQD5eFb
  artifact: /.*\.nupkg/
- provider: GitHub
  auth_token:
    secure: J3fYimU+fyAaZQ3JI4DTeRAp6dmat8KIA7O6h899eBP++3FRtO/RCeHti1HGJRzs
  artifact: /.*\.zip/
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
notifications:
  - provider: Slack
    auth_token:
      secure: sPqYbVki+502+OjRT+o3eITyiG8UDZ0Fu4M1fejZxs3O6OKtYu9JCNS9Ssw3/XjL
    channel: development